dataon = {
'selhidseats':'',
'seatrowcols':'',
'selhidrowcols':'',
'radOnewayOrReturnTrip':'R',
'matchStartPlaceR':'BANGALORE',
'matchEndPlaceR':'THRISSUR',
'datepickerO':'24/12/2015',
'datepickerR':'27/12/2015',
'selectSeatsR':'1',
'matchStartPlace':'',
'matchEndPlace':'',
'datepicker3':'',
'selectSeats':'1',
'price':'494;1012',
'time':'0;2400',
'hiddenAction':'SearchServiceR',
'selectStartPlace':'BNG',
'selectEndPlace':'TSR',
'txtJourneyDate':'24/12/2015',
'hiddenStartPlaceName':'BANGALORE',
'hiddenEndPlaceName':'THRISSUR',
'hiddenStartPlaceID':'3',
'hiddenEndPlaceID':'9',
'hiddenOnwardJourneyDate':'24/12/2015',
'hiddenCurrentDate':'06/12/2015',
'radOnwardServiceID':'26',
'hiddenTotalMales':'1',
'hiddenTotalFemales':'0',
'txtStartPlaceCode':'BNG',
'txtEndPlaceCode':'TSR',
'txtReturnDate':'27/12/2015',
'hiddenBusId':'',
'selectClass':'0',
'hiddenOnwardTimeSlab':'',
'hiddenSeatError':'NOERROR',
'SortType':'',
'Action':'',
'totalSeatsTodisplay':'1',
'seatrowcols':'',
'seatNumbersTodisplay':'',
'radOnewayOrReturnTrip':'R',
'hidExecSeatNos':'',
'hidNo_ofBerths':'0',
'hidNo_ofSeats':'0',
'hiddenReturnJourneyDate':'27/12/2015'
}
# dataret = {
# 'radOnewayOrReturnTrip':'O',
# 'matchStartPlaceR':'',
# 'matchEndPlaceR':'',
# 'datepickerO':'',
# 'datepickerR':'',
# 'selectSeatsR':'1',
# 'matchStartPlace':'THRISSUR',
# 'matchEndPlace':'BANGALORE',
# 'datepicker3':'27/12/2015',
# 'selectSeats':'1',
# 'hiddenAction':'SearchService',
# 'hiddenTotalMales':'1',
# 'hiddenTotalFemales':'0',
# 'selectStartPlace':'TSR',
# 'selectEndPlace':'BNG',
# 'txtJourneyDate':'27/12/2015',
# 'txtReturnDate':'06/12/2015',
# 'hiddenCurrentDate':'06/12/2015',
# 'hiddenOnwardJourneyDate':'27/12/2015',
# 'hiddenReturnJourneyDate':'',
# 'hiddenOnwardTimeSlab':'',
# 'hiddenStartPlaceID':'9',
# 'hiddenEndPlaceID':'3',
# 'txtStartPlaceCode':'TSR',
# 'txtEndPlaceCode':'BNG',
# 'selectClass':'0',
# 'hiddenStartPlaceName':'THRISSUR',
# 'hiddenEndPlaceName':'BANGALORE',
# 'hiddenSeatError':'NOERROR',
# 'hiddenUserType':''
# }
dataret = {
'selhidseats':'',
'seatrowcols':'',
'selhidrowcols':'',
'radOnewayOrReturnTrip':'R',
'matchStartPlaceR':'THRISSUR',
'matchEndPlaceR':'BANGALORE',
'datepickerO':'27/12/2015',
'datepickerR':'27/12/2015',
'selectSeatsR':'1',
'matchStartPlace':'',
'matchEndPlace':'',
'datepicker3':'',
'selectSeats':'1',
'price':'494;1012',
'time':'0;2400',
'hiddenAction':'SearchServiceR',
'selectStartPlace':'TSR',
'selectEndPlace':'BNG',
'txtJourneyDate':'27/12/2015',
'hiddenStartPlaceName':'THRISSUR',
'hiddenEndPlaceName':'BANGALORE',
'hiddenStartPlaceID':'3',
'hiddenEndPlaceID':'9',
'hiddenOnwardJourneyDate':'27/12/2015',
'hiddenCurrentDate':'06/12/2015',
'radOnwardServiceID':'26',
'hiddenTotalMales':'1',
'hiddenTotalFemales':'0',
'txtStartPlaceCode':'TSR',
'txtEndPlaceCode':'BNG',
'txtReturnDate':'27/12/2015',
'hiddenBusId':'',
'selectClass':'0',
'hiddenOnwardTimeSlab':'',
'hiddenSeatError':'NOERROR',
'SortType':'',
'Action':'',
'totalSeatsTodisplay':'1',
'seatrowcols':'',
'seatNumbersTodisplay':'',
'radOnewayOrReturnTrip':'R',
'hidExecSeatNos':'',
'hidNo_ofBerths':'0',
'hidNo_ofSeats':'0',
'hiddenReturnJourneyDate':'27/12/2015'
}